### ISSUE TITLE
add case insensitive search option?

### ISSUE THREAD

**Issue by haifengkao** [lokikl/vim-ctrlp-ag#2]
I found that vim-ctrlp-ag performs case-sensitive search by default.
But case-insensitive search is useful from time to time. Maybe you can add an option to allow it?

**Comment by lokikl** [comment]
Thanks for your suggestion, I kept the `<c-f>` behavior but switched the custom search `<leader>ca` to smart case. Means it will be case-insensitive when no uppercase character in the search query. See 2f7545fcc538e282c217f373ed4c1e206befbfe3.

Sorry for the late reply.
