### ISSUE TITLE
Search from ctrlp base dir rather than PWD

### ISSUE THREAD

**Issue by ratheesh** [lokikl/vim-ctrlp-ag#4]
Currently `ag` search from PWD of vim. Is it possible to search from the base directory of  current file in ctrlp?

eg: if I am searching in git repo of Linux kernel `{src}/arch/arm/omap-omap2/somefile.c`, can we search from {src}? This will reduce search time. or at least provide an option to do so.

**Comment by lokikl** [comment]
Hi Ratheesh, thanks for your suggestion.

A new option is added for changing the search base, to a specific directory or dynamically follow the current editing file. In your case, just execute the line below in your vim should work

`let g:ctrlp_ag_search_base = '{src}'`

You may also check out the updated README for details.
